server:
  port: 8484
  servlet:
    context-path: /id/allotment

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, liquibase

spring:
  application:
    name: id_allotment
  datasource:
    username: cdc_local
    password: cdc_local
    url: jdbc:postgresql://localhost:5432/capture-data-change?schema=public; # jdbc:postgresql://localhost:5432/allotment?schema=public;
    jpa:
      show-sql: true
      properties:
        hibernate:
          ddl-auto: update
          format_sql: true
          use_sql_comments: true

logging:
  level:
    org.springframework.web: DEBUG